### PR TITLE
Add escape hatches

### PR DESCRIPTION
**Pull request by ncfavier**
Adds a few missing formats and extensions, and, *most importantly*, generic ways to use formats, extensions and command-line arguments not yet supported by the crate.

### CODE REVIEW

**Comment by oli-obk** [comment]
I think we should still keep the enum nonexhaustive, so we can add more explicit variants later

**Comment by ncfavier** [comment]
Fair

**Comment by oli-obk** [comment]
Thanks!

**Comment by ncfavier** [comment]
Thanks! If you could publish a new release, that would be awesome

**Comment by oli-obk** [comment]
Yea, i'll do that likely tomorrow. Can't do it from my phone ^^

**Comment by oli-obk** [comment]
Published as 0.8.10

**Comment by ncfavier** [comment]
Thanks!

**Pull request merged**
